:spring_boot_version: current
:RestTemplate: http://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/web/client/RestTemplate.html
:HttpMessageConverter: http://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/http/converter/HttpMessageConverter.html
:toc:
:icons: font
:source-highlighter: prettify
:project_id: gs-consuming-rest

This guide walks you through the process of creating an application that consumes a
RESTful web service.

== What You Will Build

You will build an application that uses Spring's `RestTemplate` to retrieve a random
Spring Boot quotation at http://localhost:8080/api/random.

== What You Need

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/main/prereq_editor_jdk_buildtools.adoc[]

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/main/how_to_complete_this_guide.adoc[]

[[scratch]]
== Starting with Spring Initializr

You can use this https://start.spring.io/#!type=maven-project&groupId=com.example&artifactId=consuming-rest&name=consuming-rest&description=Demo%20project%20for%20Spring%20Boot&packageName=com.example.consuming-rest&dependencies=web[pre-initialized project] and click Generate to download a ZIP file. This project is configured to fit the examples in this tutorial.

To manually initialize the project:

. Navigate to https://start.spring.io.
This service pulls in all the dependencies you need for an application and does most of the setup for you.
. Choose either Gradle or Maven and the language you want to use. This guide assumes that you chose Java.
. Click *Dependencies* and select *Spring Web*.
. Click *Generate*.
. Download the resulting ZIP file, which is an archive of a web application that is configured with your choices.

NOTE: If your IDE has the Spring Initializr integration, you can complete this process from your IDE.

NOTE: You can also fork the project from Github and open it in your IDE or other editor.

[[initial]]
== Fetching a REST Resource

With project setup complete, you can create a simple application that consumes a RESTful
service.

Before you can do so, you need a source of REST resources.
We have provided an example of such a service at https://github.com/spring-guides/quoters.
You can run that application in a separate terminal and access the result at http://localhost:8080/api/random.
That address randomly fetches a quotation about Spring Boot and returns it as a JSON document.
Other valid addresses include http://localhost:8080/api/ (for all the quotations)
and http://localhost:8080/api/1 (for the first quotation), http://localhost:8080/api/2
(for the second quotation), and so on (up to 10 at present).

If you request that URL through a web browser or curl, you receive a JSON document
that looks something like this:

====
[source,java,tabsize=2script]
----
{
   type: "success",
   value: {
      id: 10,
      quote: "Really loving Spring Boot, makes stand alone Spring apps easy."
   }
}
----
====

That is easy enough but not terribly useful when fetched through a browser or through curl.

A more useful way to consume a REST web service is programmatically. To help you with that
task, Spring provides a convenient template class called {RestTemplate}[`RestTemplate`].
`RestTemplate` makes interacting with most RESTful services a one-line incantation. And it
can even bind that data to custom domain types.

First, you need to create a domain class to contain the data that you need. The following
listing shows the `Quote` record class, which you can use as your domain class:

`src/main/java/com/example/consumingrest/Quote.java`
[source,java,tabsize=2]
----
include::complete/src/main/java/com/example/consumingrest/Quote.java[]
----

This simple Java record class is annotated with `@JsonIgnoreProperties` from the Jackson JSON
processing library to indicate that any properties not bound in this type should be ignored.

To directly bind your data to your custom types, you need to specify the
variable name to be exactly the same as the key in the JSON document returned from the API.
In case your variable name and key in JSON doc do not match, you can use `@JsonProperty`
annotation to specify the exact key of the JSON document. (This example matches each
variable name to a JSON key, so you do not need that annotation here.)

You also need an additional class, to embed the inner quotation itself. The `Value` record
class fills that need and is shown in the following listing (at
`src/main/java/com/example/consumingrest/Value.java`):

====
[source,java,tabsize=2]
----
include::complete/src/main/java/com/example/consumingrest/Value.java[]
----
====

This uses the same annotations but maps onto other data fields.

== Finishing the Application

The Initalizr creates a class with a `main()` method. The following listing shows the
class the Initializr creates (at
`src/main/java/com/example/consumingrest/ConsumingRestApplication.java`):

====
[source,java]
----
include::initial/src/main/java/com/example/consumingrest/ConsumingRestApplication.java[]
----
====

Now you need to add a few other things to the `ConsumingRestApplication` class to get it to
show quotations from our RESTful source. You need to add:

* A logger, to send output to the log (the console, in this example).
* A `RestTemplate`, which uses the Jackson JSON processing library to process the incoming
data.
* A `CommandLineRunner` that runs the `RestTemplate` (and, consequently, fetches our
quotation) on startup.

The following listing shows the finished `ConsumingRestApplication` class (at
`src/main/java/com/example/consumingrest/ConsumingRestApplication.java`):

====
[source,java]
----
include::complete/src/main/java/com/example/consumingrest/ConsumingRestApplication.java[]
----
====

Finally, you need to set the server port. The quoters application uses the default 
server port, 8080, so this application cannot also use the same port. You can set 
the server port to 8081 by adding the following line to applicaiton properties 
(which the Initializr created for you):

----
server.port=8081
----

== Running the Application

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/main/build_an_executable_jar_with_both.adoc[]

You should see output similar to the following but with a random quotation:

....
2019-08-22 14:06:46.506  INFO 42940 --- [           main] c.e.c.ConsumingRestApplication           : Quote{type='success', value=Value{id=1, quote='Working with Spring Boot is like pair-programming with the Spring developers.'}}
....

NOTE: If you see an error that reads, `Could not extract response: no suitable
HttpMessageConverter found for response type [class com.example.consumingrest.Quote]`, it
is possible that you are in an environment that cannot connect to the backend service
(which sends JSON if you can reach it). Maybe you are behind a corporate proxy. Try
setting the `http.proxyHost` and `http.proxyPort` system properties to values appropriate
for your environment.

== Summary
Congratulations! You have just developed a simple REST client by using Spring Boot.

== See Also

The following guides may also be helpful:

* https://spring.io/guides/gs/rest-service/[Building a RESTful Web Service]
* https://spring.io/guides/gs/consuming-rest-angularjs/[Consuming a RESTful Web Service with AngularJS]
* https://spring.io/guides/gs/consuming-rest-jquery/[Consuming a RESTful Web Service with jQuery]
* https://spring.io/guides/gs/consuming-rest-restjs/[Consuming a RESTful Web Service with rest.js]
* https://spring.io/guides/gs/accessing-gemfire-data-rest/[Accessing GemFire Data with REST]
* https://spring.io/guides/gs/accessing-mongodb-data-rest/[Accessing MongoDB Data with REST]
* https://spring.io/guides/gs/accessing-data-mysql/[Accessing data with MySQL]
* https://spring.io/guides/gs/accessing-data-rest/[Accessing JPA Data with REST]
* https://spring.io/guides/gs/accessing-neo4j-data-rest/[Accessing Neo4j Data with REST]
* https://spring.io/guides/gs/securing-web/[Securing a Web Application]
* https://spring.io/guides/gs/spring-boot/[Building an Application with Spring Boot]
* https://spring.io/guides/gs/testing-restdocs/[Creating API Documentation with Restdocs]
* https://spring.io/guides/gs/rest-service-cors/[Enabling Cross Origin Requests for a RESTful Web Service]
* https://spring.io/guides/gs/rest-hateoas/[Building a Hypermedia-Driven RESTful Web Service]

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/main/footer.adoc[]
